FROM bufbuild/buf:1.1.0 as buf_source

FROM golang:1.17 as grpc_gateway

RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.10.0 \
    && go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.10.0

FROM namely/protoc-all:1.42_1
WORKDIR /workdir
ENV XDG_CACHE_HOME=/workdir/.cache
COPY --from=buf_source /usr/local/bin/buf /usr/local/bin/buf
COPY --from=grpc_gateway /go/bin/* /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/buf" ]